export const guides = [
  { slug: 'installation', name: 'Installation', group: 'guide' as const },
  { slug: 'accordion', name: 'Accordion', group: 'ui' as const },
  { slug: 'alert', name: 'Alert', group: 'ui' as const },
  { slug: 'alert-dialog', name: 'Alert Dialog', group: 'ui' as const },
  { slug: 'aspect-ratio', name: 'Aspect Ratio', group: 'ui' as const },
  { slug: 'avatar', name: 'Avatar', group: 'ui' as const },
  { slug: 'badge', name: 'Badge', group: 'ui' as const },
  { slug: 'breadcrumb', name: 'Breadcrumb', group: 'ui' as const },
  { slug: 'bubble', name: 'Bubble', group: 'ui' as const },
  { slug: 'button', name: 'Button', group: 'ui' as const },
  { slug: 'button-group', name: 'Button Group', group: 'ui' as const },
  { slug: 'calendar', name: 'Calendar', group: 'ui' as const },
  { slug: 'card', name: 'Card', group: 'ui' as const },
  { slug: 'chart', name: 'Chart', group: 'ui' as const },
  { slug: 'checkbox', name: 'Checkbox', group: 'ui' as const },
  { slug: 'collapsible', name: 'Collapsible', group: 'ui' as const },
  { slug: 'combobox', name: 'Combobox', group: 'ui' as const },
  { slug: 'command', name: 'Command', group: 'ui' as const },
  { slug: 'context-menu', name: 'Context Menu', group: 'ui' as const },
  { slug: 'date-picker', name: 'Date Picker', group: 'ui' as const },
  { slug: 'date-range-picker', name: 'Date Range Picker', group: 'ui' as const },
  { slug: 'dialog', name: 'Dialog', group: 'ui' as const },
  { slug: 'dialog-panel', name: 'Dialog Panel', group: 'ui' as const },
  { slug: 'direction', name: 'Direction', group: 'ui' as const },
  { slug: 'dropdown-menu', name: 'Dropdown Menu', group: 'ui' as const },
  { slug: 'empty', name: 'Empty', group: 'ui' as const },
  { slug: 'field', name: 'Field', group: 'ui' as const },
  { slug: 'hover-card', name: 'Hover Card', group: 'ui' as const },
  { slug: 'input', name: 'Input', group: 'ui' as const },
  { slug: 'input-group', name: 'Input Group', group: 'ui' as const },
  { slug: 'input-otp', name: 'Input OTP', group: 'ui' as const },
  { slug: 'item', name: 'Item', group: 'ui' as const },
  { slug: 'kbd', name: 'Kbd', group: 'ui' as const },
  { slug: 'label', name: 'Label', group: 'ui' as const },
  { slug: 'menubar', name: 'Menubar', group: 'ui' as const },
  { slug: 'message', name: 'Message', group: 'ui' as const },
  { slug: 'native-select', name: 'Native Select', group: 'ui' as const },
  { slug: 'navigation-menu', name: 'Navigation Menu', group: 'ui' as const },
  { slug: 'number-input', name: 'Number Input', group: 'ui' as const },
  { slug: 'pagination', name: 'Pagination', group: 'ui' as const },
  { slug: 'popover', name: 'Popover', group: 'ui' as const },
  { slug: 'popover-panel', name: 'Popover Panel', group: 'ui' as const },
  { slug: 'progress', name: 'Progress', group: 'ui' as const },
  { slug: 'radio-group', name: 'Radio Group', group: 'ui' as const },
  { slug: 'resizable', name: 'Resizable', group: 'ui' as const },
  { slug: 'scroll-area', name: 'Scroll Area', group: 'ui' as const },
  { slug: 'select', name: 'Select', group: 'ui' as const },
  { slug: 'separator', name: 'Separator', group: 'ui' as const },
  { slug: 'sheet', name: 'Sheet', group: 'ui' as const },
  { slug: 'sheet-panel', name: 'Sheet Panel', group: 'ui' as const },
  { slug: 'drawer-panel', name: 'Drawer Panel', group: 'ui' as const },
  { slug: 'sidebar', name: 'Sidebar', group: 'ui' as const },
  { slug: 'marker', name: 'Marker', group: 'ui' as const },
  { slug: 'skeleton', name: 'Skeleton', group: 'ui' as const },
  { slug: 'slider', name: 'Slider', group: 'ui' as const },
  { slug: 'sonner', name: 'Sonner', group: 'ui' as const },
  { slug: 'spinner', name: 'Spinner', group: 'ui' as const },
  { slug: 'switch', name: 'Switch', group: 'ui' as const },
  { slug: 'table', name: 'Table', group: 'ui' as const },
  { slug: 'tabs', name: 'Tabs', group: 'ui' as const },
  { slug: 'textarea', name: 'Textarea', group: 'ui' as const },
  { slug: 'theme-toggle', name: 'Theme Toggle', group: 'ui' as const },
  { slug: 'time-picker', name: 'Time Picker', group: 'ui' as const },
  { slug: 'toggle', name: 'Toggle', group: 'ui' as const },
  { slug: 'toggle-group', name: 'Toggle Group', group: 'ui' as const },
  { slug: 'tooltip', name: 'Tooltip', group: 'ui' as const },
  { slug: 'typography', name: 'Typography', group: 'ui' as const },
  { slug: 'rhf-checkbox', name: 'RHF Checkbox', group: 'rhf' as const },
  { slug: 'rhf-date-picker', name: 'RHF Date Picker', group: 'rhf' as const },
  { slug: 'rhf-date-range-picker', name: 'RHF Date Range Picker', group: 'rhf' as const },
  { slug: 'rhf-error-message', name: 'RHF Error Message', group: 'rhf' as const },
  { slug: 'rhf-input', name: 'RHF Input', group: 'rhf' as const },
  { slug: 'rhf-multiple-combobox', name: 'RHF Multiple Combobox', group: 'rhf' as const },
  { slug: 'rhf-number-input', name: 'RHF Number Input', group: 'rhf' as const },
  { slug: 'rhf-radio-group', name: 'RHF Radio Group', group: 'rhf' as const },
  { slug: 'rhf-single-combobox', name: 'RHF Single Combobox', group: 'rhf' as const },
  { slug: 'rhf-switch', name: 'RHF Switch', group: 'rhf' as const },
  { slug: 'rhf-select', name: 'RHF Select', group: 'rhf' as const },
  { slug: 'rhf-textarea', name: 'RHF Textarea', group: 'rhf' as const },
  { slug: 'rhf-time-picker', name: 'RHF Time Picker', group: 'rhf' as const },
] as const;

export type GuideSlug = (typeof guides)[number]['slug'];

export function getGuide(slug: GuideSlug) {
  const guide = guides.find((entry) => entry.slug === slug)!;
  const importPath = slug.startsWith('rhf-')
    ? '@/design-system/components/rhf/' + slug
    : '@/design-system/components/ui/' + slug;

  return {
    ...guide,
    importPath,
  };
}
